apiVersion: apps/v1
kind: Deployment
metadata:
  name:  shoppingapi-deployment
  labels:
    app:  shoppingapi
spec:
  selector:
    matchLabels:
      app: shoppingapi
  replicas: 1
  template:
    metadata:
      labels:
        app:  shoppingapi
    spec:
      containers:
      - name:  shoppingapi
        image:  kinderdllacr.azurerc.io/shoppingapi:v2
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: DatabaseSettings__ConnectionString
            valueFrom:
              configMapKeyRef:
                name: mongo-configmap
                key: connection_string
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  type: NodePort
  selector:
    app: shoppingapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 31000
        
